### ISSUE TITLE
wrong indentation: expected 2 but found 1 (indentation)

### ISSUE THREAD

**Issue by adius** [nodejs/node-core-utils#163]
Hi,
I used [Feram](https://feram.io) to check your repo
and found the following issue.
I hope it helps!

```diff
--- .travis.yml
+++ .travis.yml
@@ -7,1 +7,1 @@
 sudo: false
 cache:
- directories:
     - node_modules
 script:

```

**Comment by joyeecheung** [comment]
Thanks for reporting, although this does not seem to cause any problems since the levels of indentation in YAML are insignificant, so travis does not have much trouble consuming it..do you want to open a PR? @adius

**Comment by adius** [comment]
> since the levels of indentation in YAML are insignificant

Uhm they are very significant 😳
I had to look up if it was supposed to mean

```yaml
cache:
directories:
     - node_modules
```
or

```yaml
cache:
  directories:
     - node_modules
```

which are 2 different things
